### ISSUE TITLE
TimedependentPolygonmapTBWidget not working

### ISSUE THREAD

**Issue by edenden1** [argosp/Thingsboard-widgets#2]
I tried to use the new argos-maps and the TimeseriesPolygonImageMap is not working for me.
When I put it on a dashboard it writes an error:
Widget Error: TypeError: Cannot read property '_container' of undefined

**Comment by erasta** [comment]
@edenden1 can you please add code / screenshot / errormsg of that crush? thanks

I identified one possible origin of the crush, you can recheck if that helps.

**Comment by edenden1** [comment]
The error has been fixed in the last version uploaded, but there is another problem.
The polygons are shown really tiny on the upper left corner of the image instead of the right location.
The devices are shown in the right location though, according to the position function provided.

This is the position function I use:
xMinMax = [154994, 155784]
yMinMax = [563428, 564085]
newXpos = (origXPos - xMinMax[0])/(xMinMax[1]-xMinMax[0])
newYpos = (origYPos - yMinMax[0])/(yMinMax[1]-yMinMax[0])
return {x: newXpos, y: 1-newYpos};

I used your code(pubsubGeoJSONmulti.py) to publish the polygons.

**Comment by erasta** [comment]
<img width="447" alt="Screen Shot 2019-08-20 at 1 16 47 PM" src="https://user-images.githubusercontent.com/7118772/63342848-d4679600-c34c-11e9-974a-3907136cbf64.png">

the function i use is:

`return {x:(origXPos-34.5) * 50, y:(origYPos-33) * 50};`

maybe you use a different coordinate system?

**Comment by edenden1** [comment]
My position function returns x and y between 0 to 1 and not from min value to max value.

**Comment by erasta** [comment]
The polygons generated on pubsubGeoJSONmulti.py are centered on (35, 32.5) with a max radius of 0.2.
Your function turn that into (x: -196.15, y: 858.5}
Maybe change pubsubGeoJSONmulti.py to generate polygons on your coordinate system?
If that still not working, i'll fix accordingly.

**Comment by edenden1** [comment]
I changed the center accordingly.
This is my polygons center.
baseX = 155380
baseY = 563830

**Comment by erasta** [comment]
Can you push your code? or activate it so the polygons are shown on my dashboards also?

**Comment by edenden1** [comment]
import paho.mqtt.client as mqtt
from time import sleep
import random
import numpy
import geopandas
from shapely.geometry import Point, Polygon
import pprint
import json

broker = "localhost"
topic_pub = 'v1/devices/me/telemetry'

attr_pub = 'v1/devices/me/attributes'


def on_message(client, userdata, message):
    print("message received ", str(message.payload.decode("utf-8")))
    print("message topic=", message.topic)
    print("message qos=", message.qos)
    print("message retain flag=", message.retain)


def on_connect(client, userdata, flags, rc):
    print("Connected flags"+str(flags)+"result code " + str(rc))


class Device(object):

    def __init__(self, name):
        self.name = name
        self.client = mqtt.Client()
        self.client.username_pw_set(name)
        self.client.on_message = on_message
        self.client.on_connect = on_connect
        self.client.connect('localhost', 1883, 1)
        self.client.loop_start()

    def pub(self):

        props = {"A": [], "B": [], "C": []}
        for idx in range(10):
            R1 = random.randrange(10, 30)
            R2 = R1 + random.randrange(10, 20)
            R3 = R2 + random.randrange(10, 20)

            angle = numpy.arange(0, 2*numpy.pi, 0.8)
            baseX = 155380
            baseY = 563830

            X1 = baseX + R1*numpy.sin(angle)
            Y1 = baseY + R1*numpy.cos(angle)
            A1 = Polygon([[i[0], i[1]] for i in zip(X1, Y1)])
            A1s = str([[i[0], i[1]] for i in zip(X1, Y1)])

            X2 = baseX + R2*numpy.sin(angle)
            Y2 = baseY + R2*numpy.cos(angle)
            A2 = Polygon([[i[0], i[1]] for i in zip(X2, Y2)])

            X3 = baseX + R3*numpy.sin(angle)
            Y3 = baseY + R3*numpy.cos(angle)
            A3 = Polygon([[i[0], i[1]] for i in zip(X3, Y3)])

            G = geopandas.GeoDataFrame({'geometry': [A1, A2, A3]})

            totalD = G.diff()
            totalD.iloc[0] = G.iloc[0]

            for name, i in zip(["A", "B", "C"], range(totalD.size)):
                poly = totalD.iloc[i:i+1].to_json().replace('"', "'")
                sindex = idx
                polyindex = "{'index':'%s', 'name':'%s', 'value':%s}" % (idx, sindex, poly)
                props[name].append(polyindex)

        textprops = []
        for name in props:
            # proptext = props[name].to_json().replace('"', "'")
            # textprops.append('"%s": %s' % (name, proptext))

            text = '[%s]' % ",".join(props[name])
            textprops.append('"%s": "%s"' % (name, text))

        msg = '{%s}' % ",".join(textprops)
        # print(msg)
        # exit()
        self.client.publish(topic_pub, msg)


deviceName = ["A"]
DeviceList = [Device(x) for x in deviceName]

while True:
    for d in DeviceList:
        d.pub()
    sleep(5)

**Comment by edenden1** [comment]
I tried to publish to you from my computer. Not sure if it worked

**Comment by erasta** [comment]
it worked, i m working on it. some complicated problem with image maps.

**Comment by erasta** [comment]
fixed it.
the reason the polygon is so small is because the python emits a circle with a diameter < 2
<img width="464" alt="Screen Shot 2019-08-23 at 8 25 06 PM" src="https://user-images.githubusercontent.com/7118772/63614779-270eaf80-c5e4-11e9-9fd5-c9341a84beeb.png">

**Comment by erasta** [comment]
<img width="496" alt="Screen Shot 2019-08-23 at 8 29 17 PM" src="https://user-images.githubusercontent.com/7118772/63615048-b87e2180-c5e4-11e9-9fb7-533b0ddf48bb.png">
fixed the size also.

Note:
you have to sync the width/height ratio of the geo coordinates with that of the image.

**Comment by erasta** [comment]
also included [polyimagemap.js](https://github.com/argosp/Thingsboard-widgets/blob/master/TimedependentPolygonmapTBWidget/polyimagemap.js) because TB is messing up the code

**Comment by edenden1** [comment]
It seems better now. The location is still off though.

**Comment by erasta** [comment]
> It seems better now. The location is still off though.

thanks,
can you be more specific?
examples would be good.

**Comment by edenden1** [comment]
I tried your new pubsubGeoJSONmulti.py and the circles are not in their right position. The center is not where it should be.

**Comment by edenden1** [comment]
And sometimes I get an error. It Writes:

Widget Error: Cannot read property '_northEast' of undefined

**Comment by edenden1** [comment]
I noticed that without other devices the location of the polygons is correct.
When I add some devices to the map the polygons shift to another(wrong) location and their size changes too.

![Screenshot from 2019-09-02 08-31-24](https://user-images.githubusercontent.com/44123767/64092355-25b85200-cd5d-11e9-8fca-59897e006c62.png)
![Screenshot from 2019-09-02 08-31-54](https://user-images.githubusercontent.com/44123767/64092356-25b85200-cd5d-11e9-9403-e9a5c43f96ed.png)

**Comment by erasta** [comment]
just getting into it, i'll check.
But it would be extremely helpful if you logged into http://192.116.82.80:8080/dashboards/0c644790-aa68-11e9-918c-0da229dc9aca and change the dashboard to match the problem, so we'd be synchronized.

**Comment by erasta** [comment]
here i assigned the minx,miny position to the circles:
<img width="400" alt="Screen Shot 2019-09-06 at 12 40 56 PM" src="https://user-images.githubusercontent.com/7118772/64422140-9d5ee780-d0a3-11e9-8829-dfeb9ae2b500.png">
here i used the maxx, maxy position:
<img width="400" alt="Screen Shot 2019-09-06 at 12 43 21 PM" src="https://user-images.githubusercontent.com/7118772/64422261-f29af900-d0a3-11e9-9434-0c4b413e6ce0.png">
and here i used the exact center:
<img width="400" alt="Screen Shot 2019-09-06 at 12 49 09 PM" src="https://user-images.githubusercontent.com/7118772/64422611-c59b1600-d0a4-11e9-9502-0c7c0d78f869.png">

maybe you have some problems with the definitions of the position function?

**Comment by erasta** [comment]
> And sometimes I get an error. It Writes:
> 
> Widget Error: Cannot read property '_northEast' of undefined

fixed this, tell me if it happens again

**Comment by edenden1** [comment]
> here i assigned the minx,miny position to the circles:
> <img alt="Screen Shot 2019-09-06 at 12 40 56 PM" width="400" src="https://user-images.githubusercontent.com/7118772/64422140-9d5ee780-d0a3-11e9-8829-dfeb9ae2b500.png">
> here i used the maxx, maxy position:
> <img alt="Screen Shot 2019-09-06 at 12 43 21 PM" width="400" src="https://user-images.githubusercontent.com/7118772/64422261-f29af900-d0a3-11e9-9434-0c4b413e6ce0.png">
> and here i used the exact center:
> <img alt="Screen Shot 2019-09-06 at 12 49 09 PM" width="400" src="https://user-images.githubusercontent.com/7118772/64422611-c59b1600-d0a4-11e9-9502-0c7c0d78f869.png">
> 
> maybe you have some problems with the definitions of the position function?

I added a dashboard named Eden.
I put there your widget with the polygons from device Test Device A1, and the location of the device I created named edenDevice.
You can notice the polygons are not located right (not in the center as it should be).
The edenDevice location looks good though.

**Comment by erasta** [comment]
> > maybe you have some problems with the definitions of the position function?
> 
> I added a dashboard named Eden.
> I put there your widget with the polygons from device Test Device A1, and the location of the device I created named edenDevice.
> You can notice the polygons are not located right (not in the center as it should be).
> The edenDevice location looks good though.

fixed it. is it ok now?

the problem was that the dashboard was moving.

**Comment by edenden1** [comment]
It seems good now.
There are 2 other bugs I noticed though:

1. When you click the play button and moving to the dashboards screen(for example) without clicking stop. You will notice when you go back to your dashboard, that the widget is in a bugged state.

2. When you on your dashboard with the dashboard and refresh the page, all the map is getting small and going to the top of the widget, and it is stuck in this state.

**Comment by erasta** [comment]
> 1. When you click the play button and moving to the dashboards screen(for example) without clicking stop. You will notice when you go back to your dashboard, that the widget is in a bugged state.

fixed (1)

**Comment by erasta** [comment]
> 2. When you on your dashboard with the dashboard and refresh the page, all the map is getting small and going to the top of the widget, and it is stuck in this state.

didn't understand (2)

**Comment by edenden1** [comment]
> > 1. When you on your dashboard with the dashboard and refresh the page, all the map is getting small and going to the top of the widget, and it is stuck in this state.
> 
> didn't understand (2)

![Screenshot from 2019-09-09 12-24-31](https://user-images.githubusercontent.com/44123767/64519550-01c8b380-d2fd-11e9-84a5-c78c3eab53f5.png)

An example of the bugged state.
The map started at the top center, covering a small frame.
When I drag it down it cut in the middle as shown in the picture.

**Comment by erasta** [comment]
> > > 1. When you on your dashboard with the dashboard and refresh the page, all the map is getting small and going to the top of the widget, and it is stuck in this state.
> > 
> > 
> > didn't understand (2)
> 
> ![Screenshot from 2019-09-09 12-24-31](https://user-images.githubusercontent.com/44123767/64519550-01c8b380-d2fd-11e9-84a5-c78c3eab53f5.png)
> 
> An example of the bugged state.
> The map started at the top center, covering a small frame.
> When I drag it down it cut in the middle as shown in the picture.

how did you get it to be like that?
when i refresh it just returns to the initial state

**Comment by edenden1** [comment]
> > > > 1. When you on your dashboard with the dashboard and refresh the page, all the map is getting small and going to the top of the widget, and it is stuck in this state.
> > > 
> > > 
> > > didn't understand (2)
> > 
> > 
> > ![Screenshot from 2019-09-09 12-24-31](https://user-images.githubusercontent.com/44123767/64519550-01c8b380-d2fd-11e9-84a5-c78c3eab53f5.png)
> > An example of the bugged state.
> > The map started at the top center, covering a small frame.
> > When I drag it down it cut in the middle as shown in the picture.
> 
> how did you get it to be like that?
> when i refresh it just returns to the initial state

Try to refresh a few times. Sometimes it gets into this state.
You can notice the polygons are not shown when it happens.

**Comment by erasta** [comment]
> Try to refresh a few times. Sometimes it gets into this state.
> You can notice the polygons are not shown when it happens.

can't recreate, might be a platform bug
