### ISSUE TITLE
Wind markers

### ISSUE THREAD

**Issue by erasta** [argosp/Thingsboard-widgets#3]
<img width="563" alt="Screen Shot 2019-09-19 at 9 11 38 PM" src="https://user-images.githubusercontent.com/7118772/65273740-27866180-db22-11e9-925f-1139b1f264ca.png">

Need this replicated as a TimeseriesImagePolygonMap widget, so i can examine the contents of the markers.

**Comment by erasta** [comment]
<img width="338" alt="Screen Shot 2019-09-19 at 9 13 44 PM" src="https://user-images.githubusercontent.com/7118772/65273906-81872700-db22-11e9-976c-0d6a84449257.png">
Also, if i printed it correctly from the inside function on TB, the markers now contains only a lat/long, we need to add angle in degrees and power

**Comment by edenden1** [comment]
> <img alt="Screen Shot 2019-09-19 at 9 13 44 PM" width="338" src="https://user-images.githubusercontent.com/7118772/65273906-81872700-db22-11e9-976c-0d6a84449257.png">
> Also, if i printed it correctly from the inside function on TB, the markers now contains only a lat/long, we need to add angle in degrees and power

The angle come from the timeseries variable 'wind_dir'

**Comment by edenden1** [comment]
> <img alt="Screen Shot 2019-09-19 at 9 13 44 PM" width="338" src="https://user-images.githubusercontent.com/7118772/65273906-81872700-db22-11e9-976c-0d6a84449257.png">
> Also, if i printed it correctly from the inside function on TB, the markers now contains only a lat/long, we need to add angle in degrees and power

Try to print again and look for wind_dir. I added it to the data for the image map.

**Comment by erasta** [comment]
1. can you upload the python code to a new python file on the code base?
2. can you recreate the new dashboard widget as TimeseriesPolygonImageMap, instead of ImageMap? can't see what's inside.
3. what are the ts values shown above?

**Comment by erasta** [comment]
<img width="687" alt="Screen Shot 2019-09-22 at 6 34 29 PM" src="https://user-images.githubusercontent.com/7118772/65391310-1b8be100-dd68-11e9-9665-a40191f86c31.png">

**Comment by edenden1** [comment]
When I scroll in/out, the arrows are back to their original state (points to the right). And changes to something else only when the next value is published.

**Comment by erasta** [comment]
the scrolling issue is fixed.
the update issue will be fixed when you start the python process.

**Comment by erasta** [comment]
i think the update issue is also fixed, please check

**Comment by edenden1** [comment]
Can you make the arrow grow only in length and not in overall size?

**Comment by erasta** [comment]
done
also added an option on the schema to set the width of the arrow in pixels

<img width="500" alt="Screen Shot 2019-10-02 at 11 57 35 AM" src="https://user-images.githubusercontent.com/7118772/66035671-df951080-e50b-11e9-9868-33138322afe0.png">
<img width="500" alt="Screen Shot 2019-10-02 at 11 58 40 AM" src="https://user-images.githubusercontent.com/7118772/66035846-3995d600-e50c-11e9-8234-9f5191c7ab2d.png">
