### ISSUE TITLE
TimeseriesPolygonImageMap bug

### ISSUE THREAD

**Issue by edenden1** [argosp/Thingsboard-widgets#4]
I updated some attributes of my devices and now it seems the widget got broken.
1. The buttons can not be pressed (they grey)
2. The devices disappeared from the map(part of them or all of them)
3. After refresh it writes: Widget Error: Type Error: Cannot read property 'length' of null

**Comment by erasta** [comment]
can you please create a dashboard widget where this happens? everything works good for me. thanks

**Comment by erasta** [comment]
<img width="436" alt="Screen Shot 2019-09-22 at 2 01 46 PM" src="https://user-images.githubusercontent.com/7118772/65386913-8aa20f00-dd41-11e9-8870-e5638e356909.png">
looks ok to me, can you recreate?

**Comment by erasta** [comment]
might have found the bug, please check again.

**Comment by edenden1** [comment]
It seemed the problem was when I added devices with the same location as another one. Although, even if that is not the cause, it doesn't really matter for now. This case should not happened anyways, and it is working fine right now. You can try to check it if you want though.

**Comment by erasta** [comment]
> It seemed the problem was when I added devices with the same location as another one. Although, even if that is not the cause, it doesn't really matter for now. This case should not happened anyways, and it is working fine right now. You can try to check it if you want though.

i think its ok, closing the issue.
