### ISSUE TITLE
Show multiple devices on wind widgets

### ISSUE THREAD

**Issue by yehudarav** [argosp/Thingsboard-widgets#6]
Make sure that the wind widget can display multiple devices on different places.

**Comment by yehudarav** [comment]
OK, I have prepared 3 devices that send data. 

- [x] The widget should present arrows on the map (quiver). 
- [x] The wind components are u,v (and you should calculate the wind direction and speed from them). 
- [x] I remind you to add a feature to reverse the directions of u,v 
- [ ] Is it possible to define which devices of the widgets are quiver and which are regular devices that will be  used 
  like the other devices in the default TBwidget?

**Comment by erasta** [comment]
![image](https://user-images.githubusercontent.com/7118772/131221549-3ede0cd1-4679-4809-83ff-01f2b242e5ca.png)

**Comment by erasta** [comment]
![image](https://user-images.githubusercontent.com/7118772/131221565-bf4db4eb-2296-4613-af46-d2587fb820fe.png)

**Comment by erasta** [comment]
done
